name: clean_architecture_flutter
description: A new Flutter project with clean architecture.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  get_it: ^7.6.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  
  equatable: ^2.0.5
  dio: ^5.3.3
  formz: ^0.6.1
  go_router: ^11.0.0
  mime: ^1.0.4
  mocktail: ^1.0.0
  internet_connection_checker: ^1.0.0+1
  flutter_svg: ^2.0.9
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.0.4
  bloc_test: ^9.1.4

flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf


